### ISSUE TITLE
Upgrading to Netty5 Alpha2 for Android support

### ISSUE THREAD

**Issue by Armarr** [Steveice10/PacketLib#2]
Hey, love this project and MCProtocolLib.
I'm trying to get it work work on Android, and even though Netty5 boasts Android support the Alpha1 has a bug that got fixed in this commit:
https://source.jboss.org/changelog/Netty?cs=6df3bb5a79d5a7d3d7533e6cee9bcd75656fffcc

I tried upgrading myself but I'm running into problems with this change in the latest build:
https://github.com/netty/netty/commit/48f2e705d9f446f5a822ddf64bc7f86d9f96dcac

newChannel in ChannelFactory no longer takes an EventLoop it compiles fine by just removing that, though I'd like to know if there's a better solution.
~~, it obviously doesn't work.~~

~~I've never worked with netty so I have no idea what I'm doing but here's the error I get~~
~~http://screencloud.net/v/nlBI~~
~~So looking at line 44 of TcpFactory I would assume the way you bootstrap a channel has changed?~~
Any help is appreciated

**Comment by Steveice10** [comment]
Closing ahead of upcoming Alpha2 update commit.

**Comment by Steveice10** [comment]
Alpha2 update has been committed.

**Comment by RoboTricker** [comment]
I'd like to thank you all, I struggled nearly 1 month with this issue and now it's fixed! Thank You!!
