### ISSUE TITLE
Error thrown when access to /etc/hosts is denied

### ISSUE THREAD

**Issue by Camotoy** [Steveice10/PacketLib#23]
Error here: https://pastebin.com/92eXxvnn

PacketLib code: https://github.com/Steveice10/PacketLib/blob/bb12069f95e3c2edca9c875c3d49be072636ea30/src/main/java/com/github/steveice10/packetlib/tcp/TcpClientSession.java#L150

Seems like because the constructor for DnsNameResolverBuilder is not in the `try` block itself, it fails and, in our case, closes the connection (though I'm not experienced with how `try(insert code here)` blocks work). This is not on a machine I control but rather a user-reported error, though I suppose I can attempt to recreate it myself.

The reason I'm making this issue is that I propose erroring quietly and continuing with the login process, even if the SRV record cannot be found.

**Comment by Steveice10** [comment]
Does https://github.com/Steveice10/PacketLib/commit/ead6afae39f976dd115e7519f8276862f7251335 resolve the issue?

**Comment by DoctorMacc** [comment]
I'll set up a custom build and inquire now.

**Comment by Steveice10** [comment]
Going to assume this was fixed.
