### ISSUE TITLE
setReadTimeout effectiveness against server lag

### ISSUE THREAD

**Issue by tycrek** [Steveice10/PacketLib#29]
The target server that my MCProtocolLib clients connect too occasionally lags for more than 30 seconds (the default read timeout value). Would using `session.setReadTimeout(valueMoreThan30)` provide an effective strategy against disconnections due to read timeouts or would this cause more issues than it fixes?

**Comment by Steveice10** [comment]
If the lag is uncontrollable then yeah increasing the timeout values should help avoid disconnects. 30 seconds is quite a lot of lag, though.

**Comment by Steveice10** [comment]
Another consideration is, if you are suppressing the MCProtocolLib handling of keep-alive packets in favor of ones from the target server, you may run into timeout issues from the Minecraft client.

**Comment by tycrek** [comment]
> 
> 
> If the lag is uncontrollable then yeah increasing the timeout values should help avoid disconnects. 30 seconds is quite a lot of lag, though.

yeahhh it's in the anarchy community so intense lag like that isn't uncommon.

>
>
> Another consideration is, if you are suppressing the MCProtocolLib handling of keep-alive packets in favor of ones from the target server, you may run into timeout issues from the Minecraft client, so make sure you're keeping the client's connection to the proxy alive in some way.

Yes, client -> proxy is handled.

Thank you again for your help 😄
