### ISSUE TITLE
Infinite waiting in TcpSession.disconnect 

### ISSUE THREAD

**Issue by Johni0702** [Steveice10/PacketLib#6]
### What have I done?
Sending a lot of packets to a client of which at least one throw an exception during encoding.
### Expected behavior
Client gets disconnect. Exception is printed to console.
### Actual behavior
The netty thread got caught indefinitely in the `while(this.writing)` loop of `TcpSession#disconnect(String)`. Client timed out. No exception printed to console.

Due to this bug being dependent on timing it cannot be reproduced reliably. However out of 8 tests only once did it not occur.
### Explanation
Due to constantly calling `TcpSession#send(Packet)` this code gets executed extremely often: `this.writing = true;`.
Even though `this.writing` get set to false in the `exceptionCaught` method, by the time the thread reaches the `while(this.writing)` in `TcpSession#disconnect(String)`, the send method has been called yet again, resetting the `this.writing` field causing the netty thread to now wait indefinitely.
### Possible solution
Looking at the `TcpSession#send(Packet)` method suggests that it is not thread-safe. So  synchronizing it, the `TcpSession#disconnect(String)` method and the `TcpSession#exceptionCaught(ChannelHandlerContext, Throwable)` method should be fine and would resolve the issue. However I have not look too deep into the code to tell whether that has any unwanted side effects.

**Comment by Steveice10** [comment]
Should be fixed now, I added an exception boolean that's set to true when an exception is caught and halts all of the session's while loops.
