### ISSUE TITLE
Thread sleep

### ISSUE THREAD

**Issue by ensirius** [Steveice10/PacketLib#7]
https://github.com/Steveice10/PacketLib/blob/3687891770efbf55c36d94bd9c6096e2e9821f91/src/main/java/org/spacehq/packetlib/tcp/TcpSession.java#L56

Trying connect to not existing socket server causes thread wait forevor.

**Comment by Steveice10** [comment]
Cannot reproduce. Trying to connect to a non-existent server times out after a few seconds as expected.
